# It contain data realted configuration.

artifacts_root: artifacts

data_ingestion :
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Abhikkumar619/dataset/raw/main/archive%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion